import axios from "axios";
import Home from "./home";
import Head from "next/head";
export default function Index({productList,categoryList}) {
  return (
    <div>
    <Head>
      <title>e-commerce</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link
        rel="preconnect"
        href="https://fonts.gstatic.com"
        crossOrigin="true"
      />
     
    </Head>
    <> 
      <Home productList={productList}  categoryList={categoryList} />
    </>
  </div>
  );
}

export const getServerSideProps = async () => {
  const product =  await axios.get(`${process.env.NEXT_PUBLIC_API_URL}/product`)
  const categories = await axios.get(`${process.env.NEXT_PUBLIC_API_URL}/category`)

  return{
    props:{
      productList: product.data ? product.data : [],
      categoryList:categories.data ? categories.data : []
    }
  }
}
