import Home from "./home";
import Head from "next/head";
export default function Index() {
  return (
    <div>
    <Head>
      <title>e-commerce</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link
        rel="preconnect"
        href="https://fonts.gstatic.com"
        crossOrigin="true"
      />
     
    </Head>
    <> 
      <Home />
    </>
  </div>
  );
}
